name: Dataset feature request
description: You have an idea for an existing or a new dataset.
labels: ["datasets", "enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Pre-issue creation checklist
      description: Please ensure you can tick all boxes before submitting this issue.
      options:
        - label: "No duplicates of this issue have already been created."
          required: true

  - type: dropdown
    attributes:
      label: Existing or new dataset
      description: Is your feature request for an existing or for a new dataset?
      options:
        - Existing
        - New
    validations:
      required: true

  - type: input
    attributes:
      label: Name of the (new) dataset
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Data type
      description: Select the data type.
      options:
        - Fragmentation
        - Ion mobility
        - Retention time
        - Other type (describe below)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your idea
      description: >
        A clear and concise description of your idea to improve an existing dataset or
        to add a new one.
    validations:
      required: true

  - type: input
    attributes:
      label: Related tutorial
      description: >
        Does a tutorial need updating as well, or can a new tutorial be added that makes
        use of this dataset? If so, please link to the relevant tutorial issue here
        (if already created).
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context, remarks, or questions
