name: Tutorial feature request
description: You have an idea for an existing or a new tutorial.
labels: ["tutorials", "enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Pre-issue creation checklist
      description: Please ensure you can tick all boxes before submitting this issue.
      options:
        - label: "No duplicates of this issue have already been created."
          required: true

  - type: dropdown
    attributes:
      label: Existing or new tutorial
      description: Is your feature request for an existing or for a new tutorial?
      options:
        - Existing
        - New
    validations:
      required: true

  - type: input
    attributes:
      label: Name of the (new) tutorial
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Data type
      description: Select the data type the tutorial uses (or will use).
      options:
        - fragmentation
        - ion mobility
        - retention time
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe your idea
      description: >
        A clear and concise description of your idea to improve an existing tutorial or
        to add a new one.
    validations:
      required: true

  - type: input
    attributes:
      label: Related dataset
      description: >
        Does the requested change require data to be added or updated? If so, please link
        to the relevant dataset issue here (if already created).
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context, remarks, or questions
