on:
  workflow_dispatch:
  push:
    branches: [main]

name: Publish website

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          path: ./source-repo

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ProteomicsML/proteomicsml.github.io
          path: ./target-repo
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.3.340"

      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ./source-repo

      - name: Copy files to target repo
        run: |
          rm -r ./target-repo/*
          mv source-repo/_site/* ./target-repo

      - name: Add, commit, and push to target repo
        run: |
          cd ./target-repo
          git add .
          git config user.name "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git config user.email "noreply@github.com"
          git commit -am "Update from ProteomicsML/ProteomicsML@${{ github.sha }}"
          git push
