on:
  workflow_dispatch:
  pull_request_target:
    types: [ready_for_review]

name: Update notebook copies

jobs:
  generate-copies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install nbdev execnb rich

      - name: Generate copies of all notebooks without code output
        run: python .github/workflows/scripts/remove_notebook_output.py

      - name: Commit and push
        run: |
          git commit -a -m "Clean notebooks and update copies without output"
          git push
