on:
  push:
    branches: [main]

name: Update notebook copies

jobs:
  generate-copies:
    if: "! contains(github.event.head_commit.message, 'Update notebook copies without output')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install jupyter

      - name: Generate copies of all notebooks without code output
        run: python .github/workflows/scripts/remove_notebook_output.py

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PR_TOKEN }}
          commit-message: Update notebook copies without output
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: notebooks-removed-output
          delete-branch: true
          title: 'Update notebook copies without output'
          body: |
            This automated PR generates new copies of all notebooks without output.
            The automatically generated versions are prepended with an underscore
            and can be used to open in Colab for interactive usage.
          labels: |
            notebook copies
            automated pr

      - name: Approve pull request
        if: (steps.cpr.outputs.pull-request-operation == 'created' ||	steps.cpr.outputs.pull-request-operation == 'updated')
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge pull request
        if: (steps.cpr.outputs.pull-request-operation == 'created' ||	steps.cpr.outputs.pull-request-operation == 'updated')
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_PR_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
